--require("conf.feline")
require("conf.lualine")
require("conf.bufferline")
require("conf.neoscroll")
require("conf.nvim-cmp")
require("conf.indent-blankline")
require("conf.nvim-treesitter")
require("conf.nvim-ts-autotag")
