require("conf.lualine")
require("conf.bufferline")
require("conf.neoscroll")
require("conf.indent-blankline")
require("conf.nvim-treesitter")
require("conf.nvim-ts-autotag")
require("conf.nvim-autopairs")
require("conf.lsp")
require("conf.telescope")
require("conf.nvim-tree")
--vim.cmd('source /home/cody/.config/nvim/lua/conf/coc.vim')
